default_context:
#  Provide the Project name which you wanted to create
  project_name: "project broadcast"

#  Please don't change this
  _pkg_name: "{{ cookiecutter.project_name|lower|replace(' ', '') }}"

#  Please don't change this
  _read_from_file: true

#  Provide the Spring version which you wanted to use for your project from ["2.7.8", "3.0.2"]
  spring_version: "3.0.2"

#  Provide the Java version which you wanted to use for your project from [8,11,17,19]
  java_version: 19

#  Provide the DB name which you are going to use for your project from ["h2Db", "mysql", "mongoDb", "postgreSql", "oracleDb"]
  db: h2Db

#  Provide all the required dependency for your project
  _dependency:
    - jdbc

#  Provide all the resource Name which you are going to use in your project
  _resources:
    - Users
    - Customers
    - Orders


