default_context:
  project_name: "ProjectGenerator"
  _pkg_name: "{{ cookiecutter.project_name|lower|replace(' ', '') }}"
  _read_from_file: true
  version: 2.7
  _dependency:
    2.7:
      - h2
      - lombok


resource_name:
  - User
  - Customer
  - Order